### ISSUE TITLE
请问，有没有详细一些有部署教程？

### ISSUE THREAD

**Issue by chatop2020** [albyho/Tubumu.Mediasoup#1]
请问，有没有详细一些有部署教程？

**Comment by albyho** [comment]
https://github.com/albyho/Tubumu.Meeting.Demo
https://github.com/albyho/Tubumu.Abp.Meeting

**Comment by chatop2020** [comment]
请问有没有QQ群，能交流一下的？或者能不能加一下QQ交流一下？ QQ:948905   谢谢

**Comment by albyho** [comment]
已加你QQ，通过后可拉你进微信群。
