### ISSUE TITLE
该库在docker中运行失败

### ISSUE THREAD

**Issue by tianxin8206** [albyho/Tubumu.Mediasoup#2]
依赖不同的docker镜像错误信息不同
mcr.microsoft.com/dotnet/aspnet:5.0-alpine：

![image](https://user-images.githubusercontent.com/32237514/116024414-b9503c00-a680-11eb-828b-59d7bff4c1f0.png)

mcr.microsoft.com/dotnet/aspnet:5.0:

![image](https://user-images.githubusercontent.com/32237514/116024556-08966c80-a681-11eb-8866-dfb428f6d50c.png)

**Comment by albyho** [comment]
Linux alpine 过于精简，使用其他版本或安装缺少的 C/C++ runtime 之类的。
